plugins {
	id 'base'
	id 'java-library'
	id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}
apply plugin: 'io.github.gradle-nexus.publish-plugin'
['java', 'checkstyle', 'maven-publish', 'signing' ].each { apply plugin: it }

group = 'com.fifesoft.rtext'
// Note: Local JDK 21: /Library/Java/JavaVirtualMachines/jdk-21.0.5+11/Contents/Home

base {
	archivesName = 'fife.common'
}

ext.isReleaseVersion = !project.version.endsWith('SNAPSHOT')

assert JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_21)

repositories {
	mavenCentral()
}

dependencies {
	api 'org.pushing-pixels:radiance-substance:4.5.0'
	api 'org.apache.xmlgraphics:batik-rasterizer:1.19'

	testImplementation 'org.junit.jupiter:junit-jupiter:6.0.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.1'
}

wrapper {
	gradleVersion = '9.2.1'
}

checkstyle {
	toolVersion = '12.3.0'
}

tasks.withType(Javadoc) {
	options.addStringOption('Xdoclint:none', '-quiet')
}

test {
	useJUnitPlatform()
}

compileJava {
	options.release = Integer.parseInt(javaReleaseVersion)
	options.debug = true
	options.debugOptions.debugLevel = 'source,vars,lines'
	options.compilerArgs << '-Xlint:deprecation' << '-Xlint:unchecked'
}

java {
	withSourcesJar()
	withJavadocJar()
}
jar {
	manifest {
		attributes(
			'Specification-Title': 'FifeCommon',
			'Specification-Version': version,
			'Implementation-Title': 'org.fife.ui',
			'Implementation-Version': version)

	}
}



publishing {
	publications {
		maven(MavenPublication) {

			groupId = 'com.fifesoft.rtext'
			artifactId = 'fife.common'
			version = version

			from components.java

			pom {
				name = 'fife.common'
				description = 'Common UI components and utilities for Swing applications.'
				url = 'https://bobbylight.github.io/RText/'
				inceptionYear = '2003'
				packaging = 'jar'
				licenses {
					license {
						name = 'BSD-3-Clause'
						url = 'https://github.com/bobbylight/FifeCommon'
					}
				}
				developers {
					developer {
						name = 'Robert Futrell'
					}
				}
				scm {
					url = 'https://github.com/bobbylight/FifeCommon'
					connection = 'scm:git:git://github.com/bobbylight/FifeCommon'
					developerConnection = 'scm:git:git@github.com:bobbylight/FifeCommon'
					if (isReleaseVersion) {
						tag = project.version
					}
				}
			}
		}
	}
}

signing {
	// Don't require signing for e.g. ./gradlew install
	required = gradle.taskGraph.hasTask('publish') && isReleaseVersion
	sign publishing.publications.maven
}
tasks.withType(Sign) {
	onlyIf { isReleaseVersion }
}

nexusPublishing {
	repositories {
		sonatype {
			nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
			snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
			// We must defensively check for these properties so CI builds work
			username.set(project.hasProperty('sonatypeUsername') ? sonatypeUsername : 'unknown')
			password.set(project.hasProperty('sonatypePassword') ? sonatypePassword : 'unknown')
		}
	}
}
